"""Model Rating and Feedback

Revision ID: 4d6e01e7e1b5
Revises: 5a7d770dd928
Create Date: 2024-10-22 22:40:00.777454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d6e01e7e1b5'
down_revision: Union[str, None] = '5a7d770dd928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    op.create_table('rating',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('grade', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['product_id'], ['fastapi_ecommerce.products.id'],),
                    sa.ForeignKeyConstraint(['user_id'], ['fastapi_ecommerce.users.id'],),
                    sa.PrimaryKeyConstraint('id'),
                    schema='fastapi_ecommerce')
    op.create_index(op.f('ix_fastapi_ecommerce_rating_id'), 'rating', ['id'], unique=True, schema='fastapi_ecommerce')

    op.create_table('feedback',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('product_id', sa.Integer(), nullable=False),
                    sa.Column('rating_id', sa.Integer(), nullable=False),
                    sa.Column('column', sa.String(), nullable=False),
                    sa.Column('comment_date', sa.DateTime(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['rating_id'], ['fastapi_ecommerce.rating.id'],),
                    sa.ForeignKeyConstraint(['user_id'], ['fastapi_ecommerce.users.id'],),
                    sa.ForeignKeyConstraint(['product_id'], ['fastapi_ecommerce.products.id'],),
                    sa.PrimaryKeyConstraint('id'),
                    schema='fastapi_ecommerce')
    op.create_index(op.f('ix_fastapi_ecommerce_feedback_id'), 'feedback', ['id'], unique=True, schema='fastapi_ecommerce')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_ecommerce_feedback_id'), table_name='feedback', schema='fastapi_ecommerce')
    op.drop_table('feedback', schema='fastapi_ecommerce')

    op.drop_index(op.f('ix_fastapi_ecommerce_rating_id'), table_name='rating', schema='fastapi_ecommerce')
    op.drop_table('rating', schema='fastapi_ecommerce')
    # ### end Alembic commands ###
