"""supplier_id

Revision ID: 5a7d770dd928
Revises: 68a1a6a568bf
Create Date: 2024-10-21 22:56:33.791400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a7d770dd928'
down_revision: Union[str, None] = '68a1a6a568bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('supplier_id', sa.Integer(), nullable=True), schema='fastapi_ecommerce')
    sa.ForeignKeyConstraint(['supplier_id'], ['fastapi_ecommerce.users.id'], )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(table_name='products', column_name='supplier_id', schema='fastapi_ecommerce')

    # ### end Alembic commands ###
