"""Create model User

Revision ID: 68a1a6a568bf
Revises: bdc1d83b7d6d
Create Date: 2024-10-20 09:10:53.951198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68a1a6a568bf'
down_revision: Union[str, None] = 'bdc1d83b7d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_supplier', sa.Boolean(), nullable=False),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='fastapi_ecommerce'
    )
    op.create_index(op.f('ix_fastapi_ecommerce_users_id'), 'users', ['id'], unique=False, schema='fastapi_ecommerce')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_ecommerce_users_id'), table_name='users', schema='fastapi_ecommerce')
    op.drop_table('users', schema='fastapi_ecommerce')
    # ### end Alembic commands ###
