"""Init migrate

Revision ID: 8d4caccc0242
Revises: 
Create Date: 2024-10-23 19:41:41.519770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d4caccc0242'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['fastapi_ecommerce.category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_ecommerce'
    )
    op.create_index(op.f('ix_fastapi_ecommerce_category_id'), 'category', ['id'], unique=False, schema='fastapi_ecommerce')
    op.create_index(op.f('ix_fastapi_ecommerce_category_slug'), 'category', ['slug'], unique=True, schema='fastapi_ecommerce')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_supplier', sa.Boolean(), nullable=False),
    sa.Column('is_customer', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='fastapi_ecommerce'
    )
    op.create_index(op.f('ix_fastapi_ecommerce_users_id'), 'users', ['id'], unique=False, schema='fastapi_ecommerce')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['fastapi_ecommerce.category.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['fastapi_ecommerce.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_ecommerce'
    )
    op.create_index(op.f('ix_fastapi_ecommerce_products_id'), 'products', ['id'], unique=False, schema='fastapi_ecommerce')
    op.create_index(op.f('ix_fastapi_ecommerce_products_slug'), 'products', ['slug'], unique=True, schema='fastapi_ecommerce')
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['fastapi_ecommerce.products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fastapi_ecommerce.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_ecommerce'
    )
    op.create_index(op.f('ix_fastapi_ecommerce_rating_id'), 'rating', ['id'], unique=False, schema='fastapi_ecommerce')
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('rating_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('comment_date', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['fastapi_ecommerce.products.id'], ),
    sa.ForeignKeyConstraint(['rating_id'], ['fastapi_ecommerce.rating.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fastapi_ecommerce.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_ecommerce'
    )
    op.create_index(op.f('ix_fastapi_ecommerce_feedback_id'), 'feedback', ['id'], unique=False, schema='fastapi_ecommerce')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_ecommerce_feedback_id'), table_name='feedback', schema='fastapi_ecommerce')
    op.drop_table('feedback', schema='fastapi_ecommerce')
    op.drop_index(op.f('ix_fastapi_ecommerce_rating_id'), table_name='rating', schema='fastapi_ecommerce')
    op.drop_table('rating', schema='fastapi_ecommerce')
    op.drop_index(op.f('ix_fastapi_ecommerce_products_slug'), table_name='products', schema='fastapi_ecommerce')
    op.drop_index(op.f('ix_fastapi_ecommerce_products_id'), table_name='products', schema='fastapi_ecommerce')
    op.drop_table('products', schema='fastapi_ecommerce')
    op.drop_index(op.f('ix_fastapi_ecommerce_users_id'), table_name='users', schema='fastapi_ecommerce')
    op.drop_table('users', schema='fastapi_ecommerce')
    op.drop_index(op.f('ix_fastapi_ecommerce_category_slug'), table_name='category', schema='fastapi_ecommerce')
    op.drop_index(op.f('ix_fastapi_ecommerce_category_id'), table_name='category', schema='fastapi_ecommerce')
    op.drop_table('category', schema='fastapi_ecommerce')
    # ### end Alembic commands ###
