"""Initial migration

Revision ID: bdc1d83b7d6d
Revises: 
Create Date: 2024-10-17 20:56:38.062342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc1d83b7d6d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['fastapi_ecommerce.category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_ecommerce'
    )
    op.create_index(op.f('ix_fastapi_ecommerce_category_id'), 'category', ['id'], unique=False, schema='fastapi_ecommerce')
    op.create_index(op.f('ix_fastapi_ecommerce_category_slug'), 'category', ['slug'], unique=True, schema='fastapi_ecommerce')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['fastapi_ecommerce.category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi_ecommerce'
    )
    op.create_index(op.f('ix_fastapi_ecommerce_products_id'), 'products', ['id'], unique=False, schema='fastapi_ecommerce')
    op.create_index(op.f('ix_fastapi_ecommerce_products_slug'), 'products', ['slug'], unique=True, schema='fastapi_ecommerce')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fastapi_ecommerce_products_slug'), table_name='products', schema='fastapi_ecommerce')
    op.drop_index(op.f('ix_fastapi_ecommerce_products_id'), table_name='products', schema='fastapi_ecommerce')
    op.drop_table('products', schema='fastapi_ecommerce')
    op.drop_index(op.f('ix_fastapi_ecommerce_category_slug'), table_name='category', schema='fastapi_ecommerce')
    op.drop_index(op.f('ix_fastapi_ecommerce_category_id'), table_name='category', schema='fastapi_ecommerce')
    op.drop_table('category', schema='fastapi_ecommerce')
    # ### end Alembic commands ###
